# Generated by Django 5.0.4 on 2024-04-23 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crn", models.CharField(max_length=10)),
                ("course_code", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("professor", models.CharField(max_length=100)),
                ("fees", models.CharField(blank=True, max_length=10, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("meetday", models.CharField(blank=True, default="", max_length=10)),
                (
                    "start_time",
                    models.CharField(
                        blank=True, default="By Arrangement", max_length=20
                    ),
                ),
                (
                    "end_time",
                    models.CharField(
                        blank=True, default="By Arrangement", max_length=20
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="myapi.course",
                    ),
                ),
            ],
        ),
    ]
