# Generated by Django 5.0.4 on 2024-04-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="end_date",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="course",
            name="start_date",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="session",
            name="end_date",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="session",
            name="start_date",
            field=models.CharField(max_length=20),
        ),
    ]
